AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "EC API public access: TLS, CDN, DNS"

Resources:
  AuthHeaderToQueryStringFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/ECApiLambdaExecutionRole"
      CodeUri: ./api_endpoints/lambda_edge/auth_header_to_query
      Handler: handler.lambda_handler
      Runtime: python3.12
      AutoPublishAlias: live
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt MyDLQ.Arn
      ReservedConcurrentExecutions: 100
      VpcConfig:
        SecurityGroupIds:
          - sg-xxx
        SubnetIds:
          - subnet-xxx
  MyDLQ:
    Type: AWS::SQS::Queue
    Properties:
      KmsMasterKeyId: alias/aws/sqs

Outputs:
  AuthHeaderToQueryStringFunctionVersion:
    Description: The version ARN of the ID of the AuthHeaderToQueryStringFunction
    Value: !Ref AuthHeaderToQueryStringFunction.Version
    Export:
      Name: "AuthHeaderToQueryString"
