build-V1VotingInformationFunction:
	cp -r . $(ARTIFACTS_DIR)/
	pip install --break-system-packages setuptools
	pip install --upgrade pip
	pip install --use-pep517 -r requirements.txt -t "$(ARTIFACTS_DIR)/"
