version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  install_and_update_dependencies:
    docker:
    - image: circleci/python:3.8.6
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v2-dependencies-{{ checksum "Pipfile.lock" }}
        - v2-dependencies-default
    - run: &install-pipenv sudo pip install pipenv --quiet --no-input
    - run: pipenv install --dev
    - run: pipenv check # before save_cache so an insecure cache is never saved
    - save_cache:
        when: on_success
        paths:
        - ~/.local/share/virtualenvs/
        key: v2-dependencies-{{ checksum "Pipfile.lock" }}

  run-tests:
    docker:
    - image: circleci/python:3.8.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Pipfile.lock" }}
          - v2-dependencies-default
      - run: *install-pipenv
      - run:
          command: pipenv run black-check
          name: Black
      - run:
          command: pipenv run pytest --flakes
          name: Flakes
      - run:
          command: pipenv run pytest --junitxml=test-results/junit.xml
          name: Run Tests
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results

workflows:
  main:
    jobs:
      - install_and_update_dependencies
      - run-tests:
          requires:
          - install_and_update_dependencies # tests need installed dev package set
