# Generated by Django 2.2.19 on 2021-03-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.mixins


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "updated_at",
                    users.mixins.AutoDateTimeField(
                        default=django.utils.timezone.now
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="To help identify your key", max_length=255
                    ),
                ),
                (
                    "usage_reason",
                    models.TextField(
                        help_text="Short description of the usage reason for this key"
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
