# Generated by Django 2.2.19 on 2021-03-05 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_apikey"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
            },
        ),
    ]
