# Generated by Django 2.2.24 on 2021-08-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20210305_1213"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(
                default="",
                help_text="Either your name or an organisation name",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
