[project]
name = "api-auth"
version = "0.0.0"
description = "API endpoint for handling token auth"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "psycopg2-binary==2.9.10"
]

[tool.uv]
package = false
